show databases;
use sakila;
show tables;
desc actor_info;
select * from actor_info;
select actor_id from actor_info;
select actor_id+4 from actor_info;
desc actor_info;
select * from actor_info where actor_id>2;
select film_info,actor_id from actor_info where actor_id<10;
show columns from actor;
show columns from actor_info;
show databases;
desc actor;
show columns from actor;
select *from actor where actor_id=7;
select database();
select* from sakila.actor;
show databases;
use sakila;
show tables;
select * from language;
select * from language where name='english';
select * from language where language_id>3;
select * from language where language_id!=3;
select * from language where name>"";
select * from actor;
select * from film where title like '%';
select database();
show tables;
select * from film;
select * from film where title like "%";
select *from film where title like "%dinosaur%";
select * from film where title like"a_%
";
select * from film where title like "a_e%";
select * from film where title like "%_ac%";
select * from film where title like "%_a_a";
select * from film where title like '_u%m__';
show databases;
select * from sakila.actor;
use sakila;
show columns from sakila.actor;
select * from actor;
select * from actor where actor_id=3 or first_name like "ed";
select * from actor_info;
select * from actor_info where film_info like "animation%" and first_name like "%e";
select * from actor_info where film_info like "animation%" and first_name="goldie" or first_name="nick";
select * from actor_info;
select * from actor_info where (film_info like "animation%" or film_info like "children%") and first_name="meg";
select * from actor_info where actor_id between 1 and 5;
select * from actor_info where first_name between "b" and "eu"; 
select * from actor_info where actor_id in(22,24);
select * from actor_info where (actor_id between 2 and 7)and (first_name ="nick" or first_name="ed");
select * from actor_info where (last_name not like "%a%" and first_name not like "%i%") or actor_id between (10 and 20);



-- practicing the all classes
show databases;
use sakila;
show tables;
describe actor;
desc actor;
show columns  from actor;
select * from actor;
select first_name from actor;
select actor_id,first_name from actor;
select * from actor_info;
select actor_id,last_name from actor_info;
select actor_id,actor_id*10,last_name,last_name*10,first_name*10 from actor_info;
select actor_id,first_name from actor_info where actor_id=2;
select actor_id,first_name,Last_name from actor_info  where actor_id>2;
select actor_id,first_name,last_name from actor_info where first_name='nick'order by last_name desc;
show columns from actor;
desc actor;
select * from actor;
select * from sakila.actor;
show tables;
select * from language;
select * from language where name='English';
select * from language where name!='English';
select * from language where name>'';
select * from actor where first_name>'ee';
select * from film where title like '%da';
select * from film where title like 'a_n%';
select * from actor where first_name='nick' and actor_id between 2 and 44 ;
select * from actor_info;
select * from actor_info where film_info like 'Animation%' and first_name like 'goldie1' or first_name like 'nick';
select * from actor where first_name='nick' or actor_id;
select * from actor_info where film_info like 'Animation%' or first_name like 'goldie' and first_name like 'nick';
select * from actor_info where film_info like "Animation%" or first_name="goldie" and first_name ="nick";
select category,rating,title from film_list where (category like"sci-fi" or category like "family") and rating like "pg";
select (2+2)*3;
select * from actor where first_name between 'b' and 'de' order by first_name;
select * from actor where not actor_id=1;
select * from actor where first_name not like '%a%' and last_name not like '%e%';
use sakila;
select * from actor;
select row_number() over(order by first_name asc) as table_rank,first_name from actor;